# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings
#port: 4040

permalink: /:title/ 
production_url: https://www.evanlin.com
gems: ['jekyll-lunr-js-search']
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
paginate: 6 # pagination based on number of posts
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown
google_analytics: UA-54721520-1

title: Blog E
description: Attitude is everything
author:
  name: Evan
  email: evanslin@gmail.com
  github: kkdai
  twitter: Evan_Lin
  linkedin: evanlin1977
  bio: Attitude is everything
  email_md5: 670eb312a14e540fee9f24d740275774

rss_path: feed.xml
archive_path: archive
categories_path: categories
tags_path: tags
BASE_PATH: https://www.evanlin.com

gems:
  - jekyll-paginate
